version: "3.9"

services:

  database:
    image: "mongo:4.4"
    ports:
    - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"

  events:
    image: "rabbitmq:3.8"
    ports:
    - "5672"
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "root"

  accounts:
    image: "golang:1.15"
    ports:
    - "8000"
    volumes:
    - "./services/accounts:/go"
    command: ["go", "run", "main.go"]
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      PORT: "8000"
      XDG_CACHE_HOME: "/tmp/.cache"
