version: "3.9"

services:

  database:
    image: "mongo:4.4"
    ports:
    - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"

  events:
    image: "rabbitmq:3.8"
    ports:
    - "5672"
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "root"

  proxy:
    image: "traefik:2.3"
    ports:
    - "80:80"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
    - "--entrypoints.web.address=:80"
    - "--log.level=DEBUG"
    - "--providers.docker.exposedbydefault=false"
    - "--providers.docker=true"

  accounts:
    image: "golang:1.15"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.accounts.rule=Host(`accounts.thundera.localhost`)"
    - "traefik.port=8000"
    ports:
    - "8000"
    volumes:
    - "./services/accounts:/app"
    working_dir: "/app"
    command: ["go", "run", "main.go"]
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      PORT: "8000"
      XDG_CACHE_HOME: "/tmp/.cache"
    depends_on:
    - "proxy"
