version: "3.9"

services:

  database:
    image: "mongo:4.4"
    ports:
    - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"

  events:
    image: "rabbitmq:3.8"
    ports:
    - "5672"
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "root"
